version: '3'
services:
  monguito:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=santiago
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"

